name: learningbff-stack

services:
  postgres:
    image: postgres:latest
    container_name: learningbff-postgres
    environment:
      POSTGRES_DB: LearningBff
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    networks:
      - learningbff-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d LearningBff"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  db-migrator:
    container_name: learningbff-db-migrator
    image: learningbff-db-migrator
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    command: ["--migrate-database"]
    environment:
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=LearningBff;Username=postgres;Password=postgres"
    networks:
      - learningbff-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  web:
    container_name: learningbff-web
    image: learningbff-web
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    environment:
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=LearningBff;Username=postgres;Password=postgres"
      App__SelfUrl: http://localhost:8080
      App__HealthCheckUrl: /health-status
      AuthServer__Authority: http://localhost:8080
    ports:
      - "8080:8080"
    networks:
      - learningbff-network
    depends_on:
      db-migrator:
        condition: service_completed_successfully
    restart: unless-stopped

networks:
  learningbff-network:
    name: learningbff-network
    driver: bridge